/// <reference types="vitest/config" />
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'path'

export default defineConfig({
  plugins: [
    vue(),
    tailwindcss(),
    VitePWA({
      // 'prompt' mode: the shell shows a non-blocking "update available" toast and only reloads when the user taps it — never mid-sale.
      registerType: 'prompt',
      // favicon.svg is referenced by index.html; precache it for offline. The
      // PNG app icons are generated by pwaAssets, so pwa-icon.svg (their source)
      // doesn't need precaching.
      includeAssets: ['favicon.svg'],
      pwaAssets: { config: true },
      manifest: {
        name:        'وافي — نظام إدارة المتجر',
        short_name:  'وافي',
        description: 'نظام إدارة متجر يعمل بدون إنترنت، عربي بالكامل، على أي جهاز تملكه.',
        lang:        'ar',
        dir:         'rtl',
        theme_color:      '#06090F',
        background_color: '#06090F',
        display:     'standalone',
        orientation: 'portrait',
        start_url:   '/',
        scope:       '/',
      },
      workbox: {
        // Precache the built shell so the app cold-starts offline (demo moment #2).
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2,wasm}'],
        // PowerSync ships a multi-MB wa-sqlite WASM blob; raise the cap so it's
        // precached rather than silently skipped.
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
        // SPA fallback: unknown routes resolve to the app shell when offline.
        navigateFallback: '/index.html',
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.googleapis.com',
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-stylesheets',
              expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 7 },
              // Stylesheet is transparent CORS (200 only); don't cache opaque
              // error responses (status 0) — avoids quota waste on flaky networks.
              cacheableResponse: { statuses: [200] },
            },
          },
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.gstatic.com',
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  server: {
    headers: {
      'Cross-Origin-Opener-Policy':   'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  optimizeDeps: {
    // PowerSync uses WASM + web workers — must be excluded from Vite pre-bundling
    exclude: ['@powersync/web', '@journeyapps/wa-sqlite'],
  },
  worker: {
    format: 'es',
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['src/__tests__/setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', 'dist', '.agents', '.claude'],
    passWithNoTests: true,
  },
})
